# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: yonycake 
email: info@yonycake.com
description: > # this means to ignore newlines until "baseurl:"
  yonycake - A place to get away with friends and family. Stop here to check out places, people, things to do, and food we enjoy to eat.
baseurl: "/" # the subpath of your site, e.g. /blog
lang: "en"
url: "yonycake.github.io/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
disqus_username:
shortname: yonycake

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
